name: Rust

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/rust.yml
      - Cargo.*
      - src/**
  pull_request:
    paths:
      - .github/workflows/rust.yml
      - Cargo.*
      - src/**
  workflow_dispatch: { }

env:
  CARGO_TERM_COLOR: always

jobs:
  Rust:
    strategy:
      fail-fast: false
      matrix:
        rust:
          # Ubuntu 20.04
          # Ubuntu 22.04
          # Ubuntu 24.04
          - 1.75.0

          - '1.76'
          - '1.77'

          # Fedora 38
          - '1.78'

          - '1.79'
          - '1.80'
          - '1.81'

          # Fedora 39
          - '1.82'

          # openSUSE 15.5
          - '1.83'

          - '1.84'

          # Fedora 40
          # Fedora 41
          # openSUSE 15.6
          - '1.85'

        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - uses: actions/checkout@v4

      - run: cargo build --verbose
        shell: bash
